version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: decloud-dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: decloud-prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    # This service is only started when explicitly requested
    profiles:
      - prod